(() => {
  const F={trust:['Trustworthy AI','#c86b67'],core:['AI Core Algorithms','#3d6fae'],application:['AI Applications','#4e9478']};
  const S={'trust|Robustness':[145,180],'trust|Security & Attacks':[245,110],'trust|Privacy & Safety':[210,245],'core|Transfer & Fairness':[350,115],'core|Optimization':[410,185],'core|Representation':[375,250],'application|Geospatial & Environment':[575,255],'application|Finance & Society':[555,165],'application|Science & Technology':[665,305]};
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const host=document.getElementById('research-map-host'); if(!host) return;
  const tones=document.createElement('style');
  tones.textContent=`.rmnode circle:first-child:not(:only-child){stroke:#2563eb!important}.rmsub{fill:#475569!important}svg text[style]{fill:#1e3a5f!important;transform:translateY(-15px)}
  @media(max-width:820px){
    .rmh{padding:14px 15px 11px!important;gap:10px!important}.rmh h2{font-size:16px!important}
    .rmy{width:100%;justify-content:flex-start!important;flex-wrap:nowrap!important;overflow-x:auto;padding-bottom:2px;-webkit-overflow-scrolling:touch}.rmy button{flex:none!important}
    .rmb{display:block!important;min-height:0!important}.rml{display:flex!important;gap:8px!important;overflow-x:auto;padding:10px 12px!important;border-right:0!important;border-bottom:1px solid #e6edf4!important;-webkit-overflow-scrolling:touch}.rml button{flex:0 0 190px!important;margin:0!important;min-height:68px}.rml button:first-child{flex-basis:205px}
    .rmw{display:flex!important;flex-direction:column!important;min-height:0!important;overflow-x:auto!important}.rmlist{position:static!important;order:2;width:auto!important;max-height:172px!important;margin:12px 12px 0!important;flex:none}.rmlist button{font-size:10px!important;padding:7px 1px!important}.rmlist b{font-size:11px!important}
    .rmw svg{order:1;display:block!important;flex:none!important;min-width:760px!important;width:760px!important;height:400px!important}.rmmeta{font-size:9px!important}
  }`;
  document.head.append(tones);
  const fallback=p=>{let t=[p.title,...(p.keywords||[]),p.abstract].join(' ').toLowerCase();let a=/geospatial|groundwater|radon|environment|finance|financial|review|golf|swing|patent|impact factor|material|hydrogen|crypto|fault diagnosis|shale gas/.test(t),r=/robust|adversarial|security|jailbreak|privacy|homomorphic|unlearning|vulnerability/.test(t);p.research_area=p.research_area||(a?'application':r?'trust':'core');if(!p.subfield){if(p.research_area==='trust')p.subfield=/security|jailbreak|vulnerability/.test(t)?'Security & Attacks':/privacy|unlearning|homomorphic/.test(t)?'Privacy & Safety':'Robustness';else if(p.research_area==='core')p.subfield=/transfer|domain adaptation|fairness/.test(t)?'Transfer & Fairness':/optimization|sharpness/.test(t)?'Optimization':'Representation';else p.subfield=/geospatial|groundwater|radon|environment/.test(t)?'Geospatial & Environment':/finance|financial|review|crypto/.test(t)?'Finance & Society':'Science & Technology'}p.map_label=p.map_label||(p.keywords||[])[0]||p.subfield;return p};
  fetch('/publication/papers.json').then(r=>r.json()).then(d=>mount((d.papers||[]).map(fallback))).catch(()=>host.remove());
  function mount(P){let years=[...new Set(P.map(p=>+p.year))].sort((a,b)=>a-b),year=years.at(-1),field='all',sub='all';let counts=Object.fromEntries(Object.keys(F).map(k=>[k,P.filter(p=>p.research_area===k).length]));
    host.innerHTML=`<style>.rm{margin:0 0 32px;border:1px solid #dbe5ef;border-radius:16px;overflow:hidden;background:#fff;color:#172b47;font-family:Pretendard,system-ui;box-shadow:0 12px 32px #19325012}.rmh{display:flex;justify-content:space-between;gap:16px;padding:18px 21px 14px;border-bottom:1px solid #e6edf4}.rmh b{display:block;font-size:10px;color:#2d63bc;letter-spacing:.12em}.rmh h2{margin:4px 0 0;font-size:18px}.rmy{display:flex;align-items:end;gap:5px;flex-wrap:wrap;justify-content:end}.rmy button,.rml button{cursor:pointer}.rmy button{border:1px solid #dce6f0;border-radius:999px;background:#fff;padding:5px 8px;color:#708299;font-size:9px;font-weight:800}.rmy .on{border-color:#2864c7;background:#e8f0ff;color:#1d4ed8}.rmb{display:grid;grid-template-columns:310px minmax(0,1fr);min-height:430px}.rml{padding:14px;background:#fbfdff;border-right:1px solid #e6edf4}.rml button{display:block;width:100%;margin-bottom:9px;border:1px solid #e0e9f2;border-left:4px solid var(--c);border-radius:10px;background:#fff;padding:11px;text-align:left}.rml button.active{border-color:var(--c);background:color-mix(in srgb,var(--c) 7%,#fff)}.rml span{display:flex;justify-content:space-between;font-size:13px;font-weight:800}.rml em,.rml small{font-style:normal;color:#61748a;font-size:10px}.rml small{display:block;margin-top:5px}.rmw{position:relative;background:#f5f9fc}.rmw svg{display:block;width:100%;height:100%}.rmlist{position:absolute;z-index:3;right:13px;top:12px;width:180px;max-height:156px;overflow:auto;border:1px solid #dae6f1;border-radius:10px;background:#fffffff0;padding:8px;box-shadow:0 6px 18px #19325018}.rmlist b{font-size:9px;color:#2864c7}.rmlist button{display:block;width:100%;border:0;border-bottom:1px solid #edf2f6;background:transparent;padding:5px 0;text-align:left;color:#4f6883;font-size:8px;font-weight:700;cursor:pointer}.rmnode{cursor:pointer}.rmmeta{font:800 8px Pretendard,system-ui;fill:#365778;paint-order:stroke;stroke:#fff;stroke-width:4px}.rmsub{font:800 9px Pretendard,system-ui;paint-order:stroke;stroke:#fff;stroke-width:4px;cursor:pointer}@media(max-width:820px){.rmh{flex-direction:column}.rmb{grid-template-columns:1fr}.rml{border-right:0;border-bottom:1px solid #e6edf4}.rmw{min-height:430px}}</style><section class="rm"><div class="rmh"><div><b>RESEARCH MAP</b><h2>Three research directions, with evolving subfields</h2></div><div class="rmy"></div></div><div class="rmb"><aside class="rml"></aside><div class="rmw"><div class="rmlist"></div><svg viewBox="70 35 700 365"></svg></div></div></section>`;
    const svg=host.querySelector('svg'),list=host.querySelector('.rmlist'),left=host.querySelector('.rml'),yb=host.querySelector('.rmy');
    const visible=p=>(field==='all'||p.research_area===field)&&(sub==='all'||p.subfield===sub),focus=p=>visible(p)&&(year==='all'||p.year===year);const label=p=>p.map_label;
    function render(){yb.innerHTML=['all',...years].map(y=>`<button data-y="${y}" class="${String(y)===String(year)?'on':''}">${y==='all'?'All':y}</button>`).join('');yb.querySelectorAll('button').forEach(b=>b.onclick=()=>{year=b.dataset.y==='all'?'all':+b.dataset.y;render()});
      left.innerHTML=`<button data-f="all" style="--c:#52667f" class="${field==='all'?'active':''}"><span>All research <em>${P.length} papers</em></span><small>Trustworthy AI · Core Algorithms · Applications</small></button>`+Object.entries(F).map(([k,[n,c]])=>`<button data-f="${k}" style="--c:${c}" class="${field===k?'active':''}"><span>${n}<em>${counts[k]} papers</em></span><small>${k==='trust'?'Safety · Security · Privacy':k==='core'?'Transfer · Representation · Optimization':'Geospatial · Finance · Society'}</small></button>`).join('');left.querySelectorAll('button').forEach(b=>b.onclick=()=>{field=b.dataset.f;sub='all';render()});
      const N=P.map((p,i)=>{let a=P.filter(q=>q.research_area===p.research_area&&q.subfield===p.subfield),j=a.indexOf(p),c=S[p.research_area+'|'+p.subfield],r=a.length===1?0:16+Math.floor(j/6)*16,ang=j*2.399;return {...p,x:c[0]+Math.cos(ang)*r,y:c[1]+Math.sin(ang)*r}}); let m=new Map(N.map(n=>[n.id,n]));let groups={};N.forEach(n=>((groups[n.research_area+'|'+n.subfield]??=[]).push(n)));svg.innerHTML='';Object.entries(F).forEach(([k,[name,c]])=>{let a=N.filter(n=>n.research_area===k),xs=a.map(n=>n.x),ys=a.map(n=>n.y),x0=Math.min(...xs)-28,x1=Math.max(...xs)+28,y0=Math.min(...ys)-28,y1=Math.max(...ys)+28;svg.insertAdjacentHTML('beforeend',`<ellipse cx="${(x0+x1)/2}" cy="${(y0+y1)/2}" rx="${Math.max(75,(x1-x0)/2)}" ry="${Math.max(65,(y1-y0)/2)}" fill="${c}" fill-opacity=".06" stroke="${c}" stroke-opacity=".3" stroke-dasharray="5 6"/><text x="${(x0+x1)/2-(k==='application'?90:0)}" y="${y0-4}" text-anchor="middle" fill="${c}" style="font:800 13px Pretendard,system-ui;paint-order:stroke;stroke:#fff;stroke-width:5px">${name}</text>`) });Object.entries(groups).forEach(([k,a])=>{let xs=a.map(n=>n.x),ys=a.map(n=>n.y),x0=Math.min(...xs)-20,x1=Math.max(...xs)+20,y0=Math.min(...ys)-18,y1=Math.max(...ys)+18,c=F[a[0].research_area][1],cx=(x0+x1)/2,cy=(y0+y1)/2,active=sub==='all'||sub===a[0].subfield;let g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<ellipse cx="${cx}" cy="${cy}" rx="${Math.max(38,(x1-x0)/2*1.45)}" ry="${Math.max(30,(y1-y0)/2*1.45)}" fill="${c}" fill-opacity="${active?.035:.012}" stroke="${c}" stroke-opacity="${active?.34:.12}"/><text class="rmsub" x="${cx}" y="${y0-7}" text-anchor="middle" fill="${c}">${a[0].subfield}</text>`;g.onclick=()=>{field=a[0].research_area;sub=a[0].subfield;render()};svg.append(g)});N.filter(focus).forEach(n=>{let g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','rmnode');g.innerHTML=`${year==='all'?'':`<circle cx="${n.x}" cy="${n.y}" r="8.7" fill="none" stroke="#f59e0b" stroke-width="2"/>`}<circle cx="${n.x}" cy="${n.y}" r="${year==='all'?3.8:5.4}" fill="${F[n.research_area][1]}" stroke="#fff" stroke-width="1.4"/>${year==='all'?'':`<text class="rmmeta" x="${n.x+(n.x>620?-8:8)}" y="${n.y-7}" text-anchor="${n.x>620?'end':'start'}">${esc(label(n))}</text>`}`;g.onclick=()=>window.location.hash='';svg.append(g)});let a=N.filter(focus);list.innerHTML=`<b>${year==='all'?'All years':year} · ${a.length} papers</b>`+a.map(n=>`<button title="${esc(n.title)}">${esc(n.title.split(':')[0])} / ${esc(n.venue||n.year)}</button>`).join('') }
    render();
  }
})();
